---
- name: Install essential packages
  apt:
    name:
      - build-essential
      - git
      - curl
      - wget
      - unzip
      - htop
      - vim
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Add NodeJS GPG key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: yes

- name: Debug Distribution Release
  debug:
    msg: "{{ ansible_distribution_release }}"

- name: Add NodeJS repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource
  become: yes

- name: Install NodeJS
  apt:
    name:
      - nodejs
    state: present
    update_cache: no
  become: yes
