```yaml
---
- name: Configure and deploy Phoenix application
  hosts: webservers
  become: yes
  vars:
    app_name: comments-app
    phoenix_port: 4000
    db_host: "{{ lookup('env', 'DB_HOST') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    app_secret_key_base: "{{ lookup('env', 'SECRET_KEY_BASE') }}"
    erlang_cookie: "{{ lookup('env', 'ERLANG_COOKIE') }}"

  roles:
    - common
    - elixir
    - nginx
    - phoenix

  tasks:
    - name: Ensure system is updated
      apt:
        update_cache: yes
        upgrade: yes
```